#!/usr/bin/env python3
"""
═══════════════════════════════════════════════════════════════════════════════
SOLUTION: Hard Exercise 1 — D3.js Bar Chart Generator
═══════════════════════════════════════════════════════════════════════════════

This solution demonstrates generating D3.js visualisations from Python,
implementing the enter-update-exit pattern with transitions and tooltips.

LICENCE
───────
© 2025 Antonio Clim. All rights reserved.
See README.md for full licence terms.
═══════════════════════════════════════════════════════════════════════════════
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


# Wong colourblind-safe palette
WONG_PALETTE = ["#0072B2", "#E69F00", "#009E73", "#CC79A7", "#F0E442", "#56B4E9", "#D55E00"]


# ═══════════════════════════════════════════════════════════════════════════════
# DATA STRUCTURES
# ═══════════════════════════════════════════════════════════════════════════════


@dataclass
class D3Config:
    """Configuration for D3.js bar chart."""

    width: int = 800
    height: int = 500
    margin_top: int = 40
    margin_right: int = 30
    margin_bottom: int = 60
    margin_left: int = 60
    bar_padding: float = 0.2
    transition_duration: int = 750
    bar_colour: str = "#0072B2"
    hover_colour: str = "#E69F00"
    font_family: str = "Arial, sans-serif"

    @property
    def inner_width(self) -> int:
        """Calculate inner width (excluding margins)."""
        return self.width - self.margin_left - self.margin_right

    @property
    def inner_height(self) -> int:
        """Calculate inner height (excluding margins)."""
        return self.height - self.margin_top - self.margin_bottom


@dataclass
class BarChartData:
    """Container for bar chart data."""

    labels: list[str]
    values: list[float]
    title: str = "Bar Chart"
    x_label: str = "Category"
    y_label: str = "Value"

    def to_json(self) -> list[dict[str, Any]]:
        """Convert to D3-compatible JSON format."""
        return [
            {"label": label, "value": value}
            for label, value in zip(self.labels, self.values)
        ]


# ═══════════════════════════════════════════════════════════════════════════════
# D3.JS TEMPLATE GENERATORS
# ═══════════════════════════════════════════════════════════════════════════════


def generate_d3_script(
    data: BarChartData,
    config: D3Config,
) -> str:
    """
    Generate D3.js script for bar chart with enter-update-exit pattern.

    Parameters
    ----------
    data : BarChartData
        Data for the bar chart.
    config : D3Config
        Configuration options.

    Returns
    -------
    str
        Complete D3.js script.
    """
    data_json = json.dumps(data.to_json(), indent=2)

    script = f"""
// ═══════════════════════════════════════════════════════════════════════════════
// D3.js Bar Chart with Enter-Update-Exit Pattern
// Generated by Python D3 Generator
// ═══════════════════════════════════════════════════════════════════════════════

const data = {data_json};

// Configuration
const config = {{
    width: {config.width},
    height: {config.height},
    margin: {{
        top: {config.margin_top},
        right: {config.margin_right},
        bottom: {config.margin_bottom},
        left: {config.margin_left}
    }},
    barPadding: {config.bar_padding},
    transitionDuration: {config.transition_duration},
    barColour: "{config.bar_colour}",
    hoverColour: "{config.hover_colour}"
}};

// Calculate inner dimensions
const innerWidth = config.width - config.margin.left - config.margin.right;
const innerHeight = config.height - config.margin.top - config.margin.bottom;

// Create SVG container
const svg = d3.select("#chart")
    .append("svg")
    .attr("width", config.width)
    .attr("height", config.height)
    .attr("viewBox", `0 0 ${{config.width}} ${{config.height}}`)
    .style("font-family", "{config.font_family}");

// Create main group with margin transform
const g = svg.append("g")
    .attr("transform", `translate(${{config.margin.left}},${{config.margin.top}})`);

// ───────────────────────────────────────────────────────────────────────────────
// SCALES
// ───────────────────────────────────────────────────────────────────────────────

// Band scale for x-axis (categorical)
const xScale = d3.scaleBand()
    .domain(data.map(d => d.label))
    .range([0, innerWidth])
    .padding(config.barPadding);

// Linear scale for y-axis (continuous)
const yScale = d3.scaleLinear()
    .domain([0, d3.max(data, d => d.value) * 1.1])  // 10% headroom
    .nice()
    .range([innerHeight, 0]);

// ───────────────────────────────────────────────────────────────────────────────
// AXES
// ───────────────────────────────────────────────────────────────────────────────

// X-axis
const xAxis = d3.axisBottom(xScale);
g.append("g")
    .attr("class", "x-axis")
    .attr("transform", `translate(0,${{innerHeight}})`)
    .call(xAxis)
    .selectAll("text")
    .attr("transform", "rotate(-45)")
    .attr("text-anchor", "end")
    .attr("dx", "-0.5em")
    .attr("dy", "0.15em");

// X-axis label
g.append("text")
    .attr("class", "axis-label")
    .attr("x", innerWidth / 2)
    .attr("y", innerHeight + config.margin.bottom - 5)
    .attr("text-anchor", "middle")
    .style("font-size", "12px")
    .text("{data.x_label}");

// Y-axis
const yAxis = d3.axisLeft(yScale);
g.append("g")
    .attr("class", "y-axis")
    .call(yAxis);

// Y-axis label
g.append("text")
    .attr("class", "axis-label")
    .attr("transform", "rotate(-90)")
    .attr("x", -innerHeight / 2)
    .attr("y", -config.margin.left + 15)
    .attr("text-anchor", "middle")
    .style("font-size", "12px")
    .text("{data.y_label}");

// ───────────────────────────────────────────────────────────────────────────────
// TOOLTIP
// ───────────────────────────────────────────────────────────────────────────────

const tooltip = d3.select("body")
    .append("div")
    .attr("class", "tooltip")
    .style("position", "absolute")
    .style("background", "white")
    .style("border", "1px solid #ccc")
    .style("border-radius", "4px")
    .style("padding", "8px 12px")
    .style("font-size", "12px")
    .style("box-shadow", "0 2px 4px rgba(0,0,0,0.1)")
    .style("pointer-events", "none")
    .style("opacity", 0);

// ───────────────────────────────────────────────────────────────────────────────
// BARS WITH ENTER-UPDATE-EXIT PATTERN
// ───────────────────────────────────────────────────────────────────────────────

function updateBars(newData) {{
    // Data join
    const bars = g.selectAll(".bar")
        .data(newData, d => d.label);

    // EXIT: Remove old elements
    bars.exit()
        .transition()
        .duration(config.transitionDuration)
        .attr("y", innerHeight)
        .attr("height", 0)
        .style("opacity", 0)
        .remove();

    // ENTER: Create new elements
    const barsEnter = bars.enter()
        .append("rect")
        .attr("class", "bar")
        .attr("x", d => xScale(d.label))
        .attr("y", innerHeight)
        .attr("width", xScale.bandwidth())
        .attr("height", 0)
        .attr("fill", config.barColour)
        .attr("rx", 2)  // Rounded corners
        .style("cursor", "pointer");

    // Add event listeners for tooltip
    barsEnter
        .on("mouseover", function(event, d) {{
            d3.select(this)
                .transition()
                .duration(150)
                .attr("fill", config.hoverColour);
            
            tooltip
                .style("opacity", 1)
                .html(`<strong>${{d.label}}</strong><br>Value: ${{d.value.toFixed(2)}}`);
        }})
        .on("mousemove", function(event) {{
            tooltip
                .style("left", (event.pageX + 15) + "px")
                .style("top", (event.pageY - 10) + "px");
        }})
        .on("mouseout", function() {{
            d3.select(this)
                .transition()
                .duration(150)
                .attr("fill", config.barColour);
            
            tooltip.style("opacity", 0);
        }});

    // UPDATE + ENTER: Transition to final state
    barsEnter.merge(bars)
        .transition()
        .duration(config.transitionDuration)
        .delay((d, i) => i * 50)  // Staggered animation
        .ease(d3.easeCubicOut)
        .attr("x", d => xScale(d.label))
        .attr("y", d => yScale(d.value))
        .attr("width", xScale.bandwidth())
        .attr("height", d => innerHeight - yScale(d.value));
}}

// Initial render
updateBars(data);

// ───────────────────────────────────────────────────────────────────────────────
// TITLE
// ───────────────────────────────────────────────────────────────────────────────

svg.append("text")
    .attr("class", "chart-title")
    .attr("x", config.width / 2)
    .attr("y", config.margin.top / 2)
    .attr("text-anchor", "middle")
    .style("font-size", "16px")
    .style("font-weight", "bold")
    .text("{data.title}");

// Export update function for external use
window.updateChart = updateBars;
"""
    return script


def generate_html_page(
    data: BarChartData,
    config: D3Config,
) -> str:
    """
    Generate complete standalone HTML page with D3.js bar chart.

    Parameters
    ----------
    data : BarChartData
        Data for the bar chart.
    config : D3Config
        Configuration options.

    Returns
    -------
    str
        Complete HTML document.
    """
    d3_script = generate_d3_script(data, config)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{data.title}</title>
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: {config.font_family};
            background: #f5f5f5;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 20px;
            min-height: 100vh;
        }}
        #chart {{
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            padding: 20px;
        }}
        .axis-label {{
            fill: #333;
        }}
        .chart-title {{
            fill: #333;
        }}
        .x-axis text, .y-axis text {{
            font-size: 11px;
            fill: #666;
        }}
        .x-axis line, .y-axis line,
        .x-axis path, .y-axis path {{
            stroke: #ccc;
        }}
        .controls {{
            margin-top: 20px;
            display: flex;
            gap: 10px;
        }}
        button {{
            padding: 8px 16px;
            border: none;
            border-radius: 4px;
            background: {config.bar_colour};
            color: white;
            cursor: pointer;
            font-size: 14px;
            transition: background 0.2s;
        }}
        button:hover {{
            background: {config.hover_colour};
        }}
        footer {{
            margin-top: 20px;
            font-size: 12px;
            color: #888;
        }}
    </style>
</head>
<body>
    <div id="chart"></div>
    <div class="controls">
        <button onclick="randomiseData()">Randomise Data</button>
        <button onclick="resetData()">Reset</button>
    </div>
    <footer>Generated with D3.js v7 | Colourblind-safe palette (Wong)</footer>

    <script>
{d3_script}

    // Demo: Randomise data function
    function randomiseData() {{
        const newData = data.map(d => ({{
            label: d.label,
            value: Math.random() * d3.max(data, x => x.value) * 1.5
        }}));
        updateChart(newData);
    }}

    // Reset to original data
    function resetData() {{
        updateChart(data);
    }}
    </script>
</body>
</html>
"""
    return html


def save_d3_chart(
    data: BarChartData,
    output_path: Path,
    config: D3Config | None = None,
) -> Path:
    """
    Generate and save D3.js bar chart as standalone HTML.

    Parameters
    ----------
    data : BarChartData
        Data for the bar chart.
    output_path : Path
        Path to save the HTML file.
    config : D3Config or None
        Configuration options (uses defaults if None).

    Returns
    -------
    Path
        Path to the saved file.
    """
    if config is None:
        config = D3Config()

    html = generate_html_page(data, config)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")

    logger.info("D3.js chart saved to %s", output_path)
    return output_path


# ═══════════════════════════════════════════════════════════════════════════════
# SAMPLE DATA GENERATORS
# ═══════════════════════════════════════════════════════════════════════════════


def generate_sample_data() -> BarChartData:
    """Generate sample research data for demonstration."""
    import numpy as np

    rng = np.random.default_rng(42)

    labels = ["Control", "Drug A", "Drug B", "Drug C", "Combination"]
    values = [45.2, 67.8, 58.3, 72.1, 81.5]

    return BarChartData(
        labels=labels,
        values=values,
        title="Treatment Efficacy Comparison",
        x_label="Treatment Group",
        y_label="Response Rate (%)",
    )


def test_solution() -> None:
    """Test the solution implementation."""
    logger.info("Testing D3.js bar chart generator...")

    # Test 1: Config creation
    config = D3Config()
    assert config.inner_width == 800 - 60 - 30
    assert config.inner_height == 500 - 40 - 60
    logger.info("✓ Config creation test passed")

    # Test 2: Data creation and JSON export
    data = BarChartData(
        labels=["A", "B", "C"],
        values=[10, 20, 30],
        title="Test Chart",
    )
    json_data = data.to_json()
    assert len(json_data) == 3
    assert json_data[0] == {"label": "A", "value": 10}
    logger.info("✓ Data creation test passed")

    # Test 3: Script generation
    script = generate_d3_script(data, config)
    assert "d3.scaleBand()" in script
    assert "d3.scaleLinear()" in script
    assert "enter()" in script
    assert "exit()" in script
    assert "transition()" in script
    logger.info("✓ Script generation test passed")

    # Test 4: HTML generation
    html = generate_html_page(data, config)
    assert "<!DOCTYPE html>" in html
    assert "d3.v7.min.js" in html
    assert "Test Chart" in html
    logger.info("✓ HTML generation test passed")

    # Test 5: File saving
    import tempfile
    with tempfile.TemporaryDirectory() as tmpdir:
        output_path = Path(tmpdir) / "test_chart.html"
        result = save_d3_chart(data, output_path, config)
        assert result.exists()
        content = result.read_text()
        assert len(content) > 1000
    logger.info("✓ File saving test passed")

    logger.info("All tests passed!")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN ENTRY POINT
# ═══════════════════════════════════════════════════════════════════════════════


def main() -> None:
    """Main entry point demonstrating the complete solution."""
    import argparse

    parser = argparse.ArgumentParser(description="D3.js bar chart generator")
    parser.add_argument("--test", action="store_true", help="Run tests")
    parser.add_argument("--output", type=Path, default="bar_chart.html", help="Output path")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    if args.test:
        test_solution()
        return

    # Generate sample data
    data = generate_sample_data()

    # Create config
    config = D3Config(
        bar_colour=WONG_PALETTE[0],
        hover_colour=WONG_PALETTE[1],
    )

    # Save chart
    output_path = save_d3_chart(data, args.output, config)
    logger.info("Open %s in a web browser to view the chart", output_path)


if __name__ == "__main__":
    main()
